name: Deployment

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: cli
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: "cli/yarn.lock"
      - name: installing yarn
        run: npm install -g yarn
      - run: yarn install --from-lockfile
      - name: Build project
        run: yarn build
      - name: format package version
        run: |
          echo "PKG_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV && cat $GITHUB_ENV && echo ${{ env.PKG_VERSION }}
      - name: upgrade package
        run: yarn version --no-git-tag-version --new-version ${{ env.PKG_VERSION }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
